# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cccc54016d344add9d5218e429225cb2c4be586e91f8675ebe03264dd0e272cc6f8a8a713629ca26c2ca8375ceb462d6e889a29a158e2f4fa112d4c1acae17dd

test:
  secret_key_base: 90fb0cfe103bc52c1cacc6a676d727ad87f070bd678f704f783ead1ba069b2476fd42533e5d0a0b5de23e74e4403ea6d8b23c242f457b23fb703d10582cd09db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
